name: C:\Users\Timothy\Anaconda\envs\FEM
dependencies:
- alabaster=0.7.7=py27_0
- babel=2.2.0=py27_0
- backports_abc=0.4=py27_0
- colorama=0.3.7=py27_0
- cycler=0.10.0=py27_0
- decorator=4.0.9=py27_0
- docutils=0.12=py27_1
- ipykernel=4.3.1=py27_0
- ipython=4.1.2=py27_1
- ipython_genutils=0.1.0=py27_0
- jedi=0.9.0=py27_0
- jinja2=2.8=py27_0
- jpeg=8d=vc9_0
- jsonschema=2.4.0=py27_0
- jupyter_client=4.2.2=py27_0
- jupyter_core=4.1.0=py27_0
- libpng=1.6.17=vc9_1
- libtiff=4.0.6=vc9_1
- markupsafe=0.23=py27_1
- matplotlib=1.5.1=np111py27_0
- mistune=0.7.2=py27_0
- mkl=11.3.1=0
- nbconvert=4.1.0=py27_0
- nbformat=4.0.1=py27_0
- numpy=1.11.0=py27_0
- openssl=1.0.2g=vc9_0
- path.py=8.1.2=py27_1
- pep8=1.7.0=py27_0
- pickleshare=0.5=py27_0
- pip=8.1.1=py27_1
- psutil=4.1.0=py27_0
- pyflakes=1.1.0=py27_0
- pygments=2.1.1=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_5
- pyreadline=2.1=py27_0
- python=2.7.11=4
- python-dateutil=2.5.2=py27_0
- pytz=2016.3=py27_0
- pyzmq=15.2.0=py27_0
- qt=4.8.7=vc9_7
- qtconsole=4.2.1=py27_0
- rope=0.9.4=py27_1
- scipy=0.17.0=np111py27_0
- setuptools=20.6.7=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.16.9=py27_2
- six=1.10.0=py27_0
- snowballstemmer=1.2.1=py27_0
- sphinx=1.3.5=py27_0
- sphinx_rtd_theme=0.1.9=py27_0
- spyder=2.3.8=py27_1
- ssl_match_hostname=3.4.0.2=py27_0
- tk=8.5.18=vc9_0
- tornado=4.3=py27_0
- traitlets=4.2.1=py27_0
- vs2008_runtime=9.00.30729.1=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=vc9_2
- pip:
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - ipython-genutils==0.1.0
  - jupyter-client==4.2.2
  - jupyter-core==4.1.0
  - sphinx-rtd-theme==0.1.9

